---
title: "covid-19 clean data"
author: "Trang Duong"
date: "9/28/2020"
output: html_document
---
<style type="text/css">
.main-container {
  max-width: 1500px;
  margin-left: auto;
  margin-right: auto;
}
</style>

```{css horizontal scrolling, echo = FALSE}
pre, code {white-space:pre !important; overflow-x:scroll !important}
html { overflow-x: scroll; }
```


```{r setup, include = FALSE}
knitr::opts_chunk$set(echo = TRUE, message = FALSE)
```

## Packages

```{r}

library(googlesheets4)
library(lubridate)
library(magrittr)
library(stringr)
library(purrr)
library(tidyr)
library(dplyr)
library(tidyverse)
```

## Functions

These 2 functions are needed to deal with the fact that some free text is in the
`date_onset` variable:

```{r}
null2na <- function(x) {
  if (is.null(x)) return(NA)
  x
}
```

```{r}
unlist_dates <- function(x) {
  x %>%
    as.data.frame() %>%
    t() %>%
    as.data.frame() %>%
    pull(V1)
}
```

## Data
```{r}
gs4_deauth()

covid_df <- data.frame(covid_confirmed) %>% 
  rename(id ='MCB',
         type_of_observation = 'Loại.giám.sát',
         full_name = 'Họ.và.tên',
         age = 'Tuổi',
         age_group = 'Nhóm.tuổi',
         gender = 'Giới',
         address = 'Địa.chỉ.nơi.ở..nơi.lưu.trú',
         province_report = "Nơi.phát.hiện",
         profession = "Nghề.nghiệp",
         commune = "Xã.phường",
         district = "Huyện.quận",
         province = "Tỉnh.tp",
         phone_number = "Số.điện.thoại",
         phone_tracking = "Đã.tracking.điện.thoại",
         nationality = "Quốc.tịch",
         infected_type = "Loại.ca.bệnh.đích",
         sus_infect_area = "Vùng.dịch",
         sus_infec_country = "Quốc.gia.có.dịch",
         flight_seat = "Chuyến.bay..số.ghế.",
         quarantine_entry = "Cách.ly.sau.nhập.cảnh",
         infector = "Tên.ca.bệnh.đích",
         infector_relationship = "Mối.quan.hệ.với.ca.bệnh.đích",
         contact_type = "Phân.loại.tiếp.xúc",
         date_last_contact = "Ngày.tiếp.xúc.cuối.cùng",
         contact_description = "Mô.tả.hoàn.cảnh.tiếp.xúc",
         admission_date = "Ngày.vào.viện",
         treating_unit = "Cơ.sở.điều.trị",
         quarantine_type = "Loại.cách.ly",
         quarantine_start_date = "Ngày.bắt.đầu.cách.ly",
         quarantine_end_date = "Ngày.chấm.dứt.cách.ly",
         onset_date = "Ngày.khởi.phát",
         symptom = "Có.triệu.chứng",
         onset_symptom = "Triệu.chứng.khởi.phát",
         number_of_test = "Số.lần.xét.nghiệm",
         comorbidity = "Bệnh.nền",
         sample1 = "Ngày.lấy.mẫu.1",
         sample2 = "Ngày.lấy.mẫu.2",
         sample3 = "Ngày.lấy.mẫu.3",
         sample4 = "Ngày.lấy.mẫu.4",
         sample5 = "Ngày.lấy.mẫu.5",
         sample6 = "Ngày.lấy.mẫu.6",
         sample7 = "Ngày.lấy.mẫu.7",
         sample8 = "Ngày.lấy.mẫu.8",
         sample9 = "Ngày.lấy.mẫu.9",
         sample10 = "Ngày.lấy.mẫu.10",
         sample11 = "Ngày.lấy.mẫu.11",
         sample12 = "Ngày.lấy.mẫu.12",
         sample13 = "Ngày.lấy.mẫu.13",
         sample14 = "Ngày.lấy.mẫu.14",
         sample15 = "Ngày.lấy.mẫu.15",
         sample16 = "Ngày.lấy.mẫu.16",
         sample17 = "Ngày.lấy.mẫu.17",
         sample18 = "Ngày.lấy.mẫu.18",
         sample19 = "Ngày.lấy.mẫu.19",
         result1 = "KQXN.1",
         result2 = "KQXN.2",
         result3 = "KQXN.3",
         result4 = "KQXN.4",
         result5 = "KQXN.5",
         result6 = "KQXN.6",
         result7 = "KQXN.7",
         result8 = "KQXN.8",
         result9 = "KQXN.9",
         result10 = "KQXN.10",
         result11 = "KQXN.11",
         result12 = "KQXN.12",
         result13 = "KQXN.13",
         result14 = "KQXN.14",
         result15 = "KQXN.15",
         result16 = "KQXN.16",
         result17 = "KQXN.17",
         result18 = "KQXN.18",
         result19 = "KQXN.19",
         date_of_discharge = "Ngày.ra.viện"  
         ) %>%
  mutate(
        type_of_observation = recode(type_of_observation, 
                                     "Ca xác định" = "confirmed_case",
                                     "Ca nghi ngờ" = "suspected_case"
                                     ),
        # infection_area = recode(infection_area,
        #                         )
        quarantine_type = recode(quarantine_type, 
                                 "Cơ sở điều trị" = "treating unit",
                                 "Tại nhà" = "at home",
                                 "Cơ sở tập trung" = "quarantine center"
                                   ),
        infected_type =  recode(infected_type,
                                 "Ổ dịch nước ngoài" = "imported",
                                 "Ca xác định"  = "confirmed case",
                                 "Ổ dịch nội địa" = "inland",
                                 "Ca tiếp xúc" = "contact",
                                 "Ca nghi ngờ" = "suspected"),
        
        gender= recode(gender, 
                       Nam = "male", 
                       Nữ = "female"),
        age_group = recode(age_group, 
                           "1.Từ 1-5" = "1. From 1-5",
                           "2.Từ 6-15" = "2.From 6-15",
                           "3.Từ 16-25" = "3.From 16-25",
                           "4.Từ 26-40" = "4.From 26-40",
                           "5.Từ 41-60" = "5.From 41-60",
                           "6.Từ 61-70" = "6.From 61-70",
                           "7.Trên 70" = "7.From 70"),
        symptom =  recode(symptom,
                          "Có" = "Yes",
                          "Không" = "No"),
        result1 = recode(result1,
                         "Âm tính" = "negative",
                         "Dương tính" = "positive"),
        result2 = recode(result2,
                         "Âm tính" = "negative",
                         "Dương tính" = "positive"),
        result3 = recode(result3,
                         "Âm tính" = "negative",
                         "Dương tính" = "positive"),
          result4 = recode(result4,
                         "Âm tính" = "negative",
                         "Dương tính" = "positive"),
          result5 = recode(result5,
                         "Âm tính" = "negative",
                         "Dương tính" = "positive"),
          result6 = recode(result6,
                         "Âm tính" = "negative",
                         "Dương tính" = "positive"),
          result7 = recode(result7,
                         "Âm tính" = "negative",
                         "Dương tính" = "positive"),
            result8 = recode(result8,
                         "Âm tính" = "negative",
                         "Dương tính" = "positive"),
          result9 = recode(result9,
                         "Âm tính" = "negative",
                         "Dương tính" = "positive"),
            result10 = recode(result10,
                         "Âm tính" = "negative",
                         "Dương tính" = "positive"),
            result11 = recode(result11,
                         "Âm tính" = "negative",
                         "Dương tính" = "positive"),
            result12 = recode(result12,
                         "Âm tính" = "negative",
                         "Dương tính" = "positive"),
            result13 = recode(result13,
                         "Âm tính" = "negative",
                         "Dương tính" = "positive"),
            result14 = recode(result14,
                         "Âm tính" = "negative",
                         "Dương tính" = "positive"),
            result15 = recode(result15,
                         "Âm tính" = "negative",
                         "Dương tính" = "positive"),
            result16 = recode(result16,
                         "Âm tính" = "negative",
                         "Dương tính" = "positive"),
            result17 = recode(result17,
                         "Âm tính" = "negative",
                         "Dương tính" = "positive"),
            result18 = as.character(result18),
            result18 = recode(result18,
                         "Âm tính" = "negative",
                         "Dương tính" = "positive"),
            result19 = as.character(result19),
            result19 = recode(result19,
                         "Âm tính" = "negative",
                         "Dương tính" = "positive")) %>%
   mutate(date_last_contact = as.Date(as.numeric(date_last_contact), origin = "1899-12-30")) %>%
   mutate(onset_date = as.Date(as.numeric(onset_date), origin = "1899-12-30")) %>%
   mutate(date_of_discharge = as.Date(date_of_discharge, origin = "1899-12-30")) %>%
   mutate(admission_date = as.Date(admission_date, origin = "1899-12-30")) %>%
   mutate(sample7 = as.Date(sample7, origin = "1899-12-30")) %>%
   mutate(sample8 = as.Date(sample8, origin = "1899-12-30")) %>%
   mutate(sample9 = as.Date(sample9, origin = "1899-12-30")) %>%
   mutate(sample10 = as.Date(sample10, origin = "1899-12-30")) %>%
   mutate(sample11 = as.Date(sample11, origin = "1899-12-30")) %>%
   mutate(sample12 = as.Date(sample12, origin = "1899-12-30")) %>%
   mutate(sample13 = as.Date(sample13, origin = "1899-12-30")) %>%
   mutate(sample14 = as.Date(sample14, origin = "1899-12-30")) %>%
   mutate(sample15 = as.Date(sample15, origin = "1899-12-30")) %>%
   mutate(sample16 = as.Date(sample16, origin = "1899-12-30")) %>%
   mutate(sample17 = as.Date(sample17, origin = "1899-12-30")) %>%
   mutate(sample18 = as.Date(sample18, origin = "1899-12-30")) %>%
   mutate(sample19 = as.Date(sample19, origin = "1899-12-30")) 


```

```{r}
covid_df %>%
  mutate_at(c("infector", "age_group", "symptom", "comorbidity"), map_chr, paste, collapse = " | ") %>% 
  write.csv2("~/Dropbox/Covid-19/covid-19/Covid-19_data.csv", quote = FALSE, row.names = FALSE)

saveRDS(covid_df, "~/Dropbox/Covid-19/covid-19/covid_df.rds")
```